Unit tests:
    stage: test
    image: node:latest
    script:
        - cd Unit_tests
        - npm ci
        - npm test
    artifacts:
        paths:
            - mochawesome-report    

API tests:
    stage: test
    image: node:latest
    script:
        - cd API_tests
        - npm ci
        - npm test

UI tests_1:
    stage: test
    image: node:18
    script:
        - cd UI_tests_1
        - npm ci
        - npm test    

UI tests_2:
    stage: test
    image: node:18
    script:
        - cd UI_tests_2
        - npm ci
        - npm test              

