default:
  image: node:18

UI_testing_1:
  stage: test
  services:
    - selenium/standalone-chrome
  script:
    - cd UI_tests_1
    - npm test --host=selenium__standalone-chrome
    
UI_testing_2:
  stage: test
  services:
    - selenium/standalone-firefox
  script:
    - cd UI_tests_2
    - npm test --host=selenium__standalone-firefox

Unit tests:
    stage: test
    script:
        - cd Unit_tests
        - npm ci
        - npm test
    artifacts:
        paths:
            - mochawesome-report    

API tests:
    stage: test
    script:
        - cd API_tests
        - npm ci
        - npm test

UI tests_1:
    stage: test
    script:
        - cd UI_tests_1
        - npm ci
        - npm test    

UI tests_2:
    stage: test
    script:
        - cd UI_tests_2
        - npm ci
        - npm test              

