Unit tests:
    stage: test
    image: node:latest
    script:
        - cd Unit_tests
        - npm ci
        - npm test
    artifacts:
        paths:
            - mochawesome-report    

API tests:
    stage: test
    image: node:latest
    script:
        - cd API_tests
        - npm ci
        - npm test

UI tests_2:
    stage: test
    image: node:latest
    script:
        - cd UI_tests_2
        - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
        - source ~/.nvm/nvm.sh
        - nvm use 18
        - npm ci
        - npm test              

