stages:
  - test

image: ghcr.io/puppeteer/puppeteer:latest

before_script:
  - npm ci

UI tests:
  stage: test
  script:
   - cd UI_tests
   - npm run test
  artifacts:
    paths:
      - /builds/nino_londaridze/homeworks-automated-testing-with-js/Unit_tests/mochawesome-report/mochawesome.json

Unit tests:
  stage: test
  script:
      - cd Unit_tests
      - npm test
  artifacts:
    paths:
     - /builds/nino_londaridze/homeworks-automated-testing-with-js/Unit_tests/mochawesome-report/mochawesome.json

API tests:
  stage: test
  script:
      - cd API_tests
      - npm test
  artifacts:
    paths:
      - /builds/nino_londaridze/homeworks-automated-testing-with-js/API_tests/mochawesome-report/mochawesome.json