Unit tests:
    stage: test
    image: node:latest
    script:
        - cd Unit_tests
        - npm ci
        - npm test

API tests:
    stage: test
    image: node:latest
    script:
        - cd API_tests
        - npm ci
        - npm test

UI tests_2:
    stage: test
    image: node:latest
    script:
        - apk add --no-cache build-base g++ cairo-dev jpeg-dev pango-dev giflib-dev
        - apk add --update --repository http://dl-3.alpinelinux.org/alpine/edge/testing libmount ttf-dejavu ttf-droid ttf-freefont ttf-liberation ttf-ubuntu-font-family fontconfig
        - cd UI_tests_2
        - npm ci
        - npm test              

