stages:
  - test

image: ghcr.io/puppeteer/puppeteer:latest

before_script:
  - npm ci

UI test_1:
  stage: test
  services:
    - name: selenium/standalone-chrome:latest 
  script:
    - cd UI_tests_1
    - npm run test