Unit tests:
    stage: test
    image: node:latest
    script:
        - cd Unit_tests
        - npm ci
        - npm test
    artifacts:
        paths:
            - mochawesome-report    

API tests:
    stage: test
    image: node:latest
    script:
        - cd API_tests
        - npm ci
        - npm test

UI tests_1:
    stage: test
    image: node:18
    before_script:
    - apt-get update
    - apt-get install -y wget gnupg
    - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
    - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
    - apt-get update
    - apt-get install -y google-chrome-stable
    script:
        - cd UI_tests_1
        - npm ci
        - npm test    

UI tests_2:
    stage: test
    image: node:18
    script:
        - cd UI_tests_2
        - npm ci
        - npm test              

