Unit tests:
    stage: test
    image: node:latest
    script:
        - cd Unit_tests
        - npm ci
        - npm test

API tests:
    stage: test
    image: node:latest
    script:
        - cd API_tests
        - npm ci
        - npm test


