stages:
  - test

image: ghcr.io/puppeteer/puppeteer:latest

before_script:
  - npm ci

UI test_1:
  stage: test
  script:
    - cd UI_tests_1
    - npm test
    
UI test_2:
  stage: test
  services:
    - selenium/standalone-firefox
  script:
    - cd UI_tests_2
    - npm test --host=selenium__standalone-firefox

Unit tests:
    stage: test
    script:
        - cd Unit_tests
        - npm test
    artifacts:
        paths:
            - /builds/nino_londaridze/homeworks-automated-testing-with-js/Unit_tests/mochawesome-report/mochawesome.json

API tests:
    stage: test
    script:
        - cd API_tests
        - npm test
    artifacts:
      paths:
          - /builds/nino_londaridze/homeworks-automated-testing-with-js/API_tests/mochawesome-report/mochawesome.json
