default:
  image: node:18

stages:
  - confidence-check
  - test

e2e:firefox:
  stage: confidence-check
  services:
    - selenium/standalone-firefox
  script:
    - npm test --host=selenium__standalone-firefox

e2e:chrome:
  stage: confidence-check
  services:
    - selenium/standalone-chrome
  script:
    - npm test --host=selenium__standalone-chrome

Unit tests:
    stage: test
    image: node:latest
    script:
        - cd Unit_tests
        - npm ci
        - npm test
    artifacts:
        paths:
            - mochawesome-report    

API tests:
    stage: test
    image: node:latest
    script:
        - cd API_tests
        - npm ci
        - npm test

UI tests_1:
    stage: test
    image: node:18
    script:
        - cd UI_tests_1
        - npm ci
        - npm test    

UI tests_2:
    stage: test
    image: node:18
    script:
        - cd UI_tests_2
        - npm ci
        - npm test              

