test-job:
    stage: test
    script:
        - echo "Running test"
        - npm test

    only: 
        - branches

    artifacts:
        paths:
            - "mochawesome-report"
        reports:
            junit: mochawesome-report/mochawesome.xml
               
